language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_install:
- docker pull resystit/bind9:latest
- docker run -d --name ${CONTAINER_NAME} -p 60053:53 -p 60053:53/udp -p 60022:22 -v $(pwd)/docker_test_files/named.conf:/etc/bind/named.conf:ro -v $(pwd)/docker_test_files/zone1.conf:/etc/bind/master/zone1.local.conf:ro -v $(pwd)/docker_test_files/zone2.conf:/etc/bind/master/zone2.local.conf:ro -v $(pwd)/docker_test_files/id_rsa_test.pub:/root/.ssh/authorized_keys:ro
- docker exec bind9_dns_audit_test sh -c "apk add --update git openssh-client openssh-server"
- docker exec bind9_dns_audit_test sh -c "chmod 700 /root/.ssh"
- docker cp $(pwd)/docker_test_files/id_rsa_host_test bind9_dns_audit_test:/etc/ssh/ssh_host_rsa_key
- docker cp $(pwd)/docker_test_files/id_rsa_host_test.pub bind9_dns_audit_test:/etc/ssh/ssh_host_rsa_key.pub
- docker exec bind9_dns_audit_test sh -c "chmod 600 /etc/ssh/ssh_host_rsa_key"
- docker exec -d bind9_dns_audit_test sh -c "/usr/sbin/sshd -D -f /etc/ssh/sshd_config"

install: pip install -r requirements.txt
script: python setup.py test
