language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_install:
  - docker build . -t bind9_dns_audit_test_bind9 -f Dockerfile_BIND9
  - >
    docker run -d --name bind9_dns_audit_test_bind9 -p 60053:53 -p 60053:53/udp -p 60022:22
    -v $(pwd)/docker_test_files/named.conf:/etc/bind/named.conf:ro
    -v $(pwd)/docker_test_files/zones:/etc/bind/master:ro
    bind9_dns_audit_test_bind9

install: pip install -r requirements.txt
script: python setup.py test
